services:
  - type: web
    name: sketch-ecommerce
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
      - key: REACT_APP_EMAIL_ENABLED
        value: "true"
      - key: REACT_APP_EMAIL_FROM
        sync: false
      - key: REACT_APP_SUPPORT_EMAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: REACT_APP_RECAPTCHA_SITE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/index.html
      - type: rewrite
        source: /*
        destination: /index.html 